#!/bin/bash
#
# Xcode checks — the build-tool plugin's `XcodeBuildToolPlugin` path, black-box.
#
# The plugin lane next door covers the SPM path. Everything it covers goes
# through `PackagePlugin`, which is a different API with a different source of
# truth: an Xcode project hands the plugin no package graph, no dependency edges
# and no shipped templates. This lane is the only place that half of
# `SourcerySwiftCodegenPlugin.swift` is run rather than merely typechecked.
#
#   green project  XcodeFixture/ — four macOS framework targets, built one
#                  scheme at a time, whose synthesized configs and generated
#                  code the gates below read.
#   red project    XcodeFixtureRed/BareName/ — must FAIL, for a reason this
#                  script matches on. A project of its own, for the reason the
#                  plugin lane's red controls are separate packages: build
#                  planning runs the plugin for every target being built.
#
# The `.xcodeproj` of each is generated by `xcodegen` from a committed
# `xcodegen.yml` and is not itself committed
# (specs/001-plugin-source-discovery/followup-xcode-lane.md, F3).
#
# Usage:
#   Tests/Checks/run-xcode-checks.sh          # run the gates
#   Tests/Checks/run-xcode-checks.sh --keep   # keep the plugin outputs too
#                                             # (faster, but nothing runs cold)
#
# Needs Xcode, `xcodegen` (`brew install xcodegen`) and, once, the network — the
# fixtures resolve this package, which pulls swift-argument-parser and the pinned
# Sourcery artifact bundle. Both land in .build/xcode-checks/SourcePackages,
# shared by every project here. No simulator.

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GIT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

WORK_DIR="$GIT_ROOT/.build/xcode-checks"
SPM_DIR="$WORK_DIR/SourcePackages"
DD="$WORK_DIR/DD"
FIXTURE_DIR="$SCRIPT_DIR/XcodeFixture"
RED_DIR="$SCRIPT_DIR/XcodeFixtureRed"

KEEP=0
[ "$1" = "--keep" ] && KEEP=1

FAILURES=0
fail() { echo "  FAIL: $1"; FAILURES=$((FAILURES + 1)); }
pass() { echo "  ok: $1"; }

# ── Preflight ─────────────────────────────────────────────────────

if ! command -v xcodegen > /dev/null; then
  echo "xcodegen is not installed, and this lane generates its projects with it."
  echo "  brew install xcodegen"
  exit 1
fi

mkdir -p "$WORK_DIR"

# ── Helpers ───────────────────────────────────────────────────────

# The synthesized copy of <config> for <target>, under <derived-data>.
synthesized() {   # derived-data target config
  find "$1/Build/Intermediates.noindex/BuildToolPluginIntermediates" \
    -path "*/$2/*/.sourceryConfigs/$3" -type f 2>/dev/null | head -1
}

# A file Sourcery generated for <target> from <config-directory>.
generated() {   # derived-data target config-directory file
  find "$1/Build/Intermediates.noindex/BuildToolPluginIntermediates" \
    -path "*/$2/*/.generatedFiles/$3/$4" -type f 2>/dev/null | head -1
}

# The lines of a `sources:`/`templates:` block that the plugin wrote: quoted
# absolute paths, one per line, unquoted here for legibility. An entry the author
# wrote is not quoted, so it does not appear — which is what makes this the
# closure and nothing else.
block_paths() {   # file key
  awk -v key="$2" '
    $0 ~ "^" key ":" { inblock = 1; next }
    /^[A-Za-z_]/     { inblock = 0 }
    inblock && /^[ \t]*- "/ {
      line = $0
      sub(/^[ \t]*- "/, "", line)
      sub(/"[ \t]*$/, "", line)
      print line
    }
  ' "$1"
}

# Every line of <original> is present in <synthesized>, in the same order, except
# the lines named after the two file arguments — the lines the plugin is allowed
# to rewrite. Comments, blank lines and untouched keys have to survive byte for
# byte.
check_passthrough() {
  local original="$1" synthesized="$2"; shift 2
  local skiplist="$WORK_DIR/passthrough-rewritable"
  printf '%s\n' "$@" > "$skiplist"
  awk -v skipfile="$skiplist" -v origfile="$original" '
    FILENAME == skipfile { skip[$0] = 1; next }
    FILENAME == origfile { orig[++o] = $0; next }
    { syn[++s] = $0 }
    END {
      j = 1
      for (i = 1; i <= o; i++) {
        if (orig[i] in skip) continue
        found = 0
        while (j <= s) { if (syn[j++] == orig[i]) { found = 1; break } }
        if (!found) { print "missing or out of order: [" orig[i] "]"; exit 1 }
      }
    }
  ' "$skiplist" "$original" "$synthesized"
}

xcbuild() {   # project scheme derived-data log
  xcodebuild build \
    -project "$1" \
    -scheme "$2" \
    -destination 'platform=macOS' \
    -derivedDataPath "$3" \
    -clonedSourcePackagesDirPath "$SPM_DIR" \
    -skipPackagePluginValidation \
    -skipMacroValidation \
    > "$4" 2>&1
}

# ── Generate ──────────────────────────────────────────────────────
echo "── generate ──"
for spec in "$FIXTURE_DIR/xcodegen.yml" "$RED_DIR"/*/xcodegen.yml; do
  dir="$(dirname "$spec")"
  if ! xcodegen generate --spec "$spec" --project "$dir" -q; then
    echo "FAIL: xcodegen could not generate $spec"
    exit 1
  fi
  echo "  generated $(basename "$dir")/$(basename "$dir").xcodeproj"
done

if [ "$KEEP" = "0" ]; then
  # Keep the resolved packages and the downloaded artifact bundle — those live in
  # SPM_DIR, outside the derived data — and drop everything the build produced, so
  # the gates below read a cold run rather than a file left by the last one.
  rm -rf "$DD/Build"
fi

# ── 1. Runs ───────────────────────────────────────────────────────
# The whole path, end to end: a `.Sourcery.*.yml` reaches the plugin through the
# target's own directory, is copied with the closure spliced and `output:`
# supplied, Sourcery runs, and Xcode compiles what it wrote into the target.
echo ""
echo "── runs ──"
COLD_START=$SECONDS
APP_LOG="$WORK_DIR/app-build.log"
if ! xcbuild "$FIXTURE_DIR/XcodeFixture.xcodeproj" App "$DD" "$APP_LOG"; then
  grep -E 'error:' "$APP_LOG" | head -20
  echo "FAIL: the App scheme did not build — every gate below depends on it"
  exit 1
fi
COLD_SECONDS=$((SECONDS - COLD_START))
echo "  built in ${COLD_SECONDS}s (cold plugin outputs)"

APP_CONFIG="$(synthesized "$DD" App .Sourcery.Mocks.yml)"
if [ -n "$APP_CONFIG" ] && [ -f "$APP_CONFIG" ]; then
  pass "the config was discovered and a synthesized copy written"
else
  echo "FAIL: the plugin wrote no synthesized config for App"
  exit 1
fi
APP_MOCK="$(generated "$DD" App Sourcery.Mocks Mocks.generated.swift)"
if [ -n "$APP_MOCK" ] && grep -q 'class ProfilePersistingMock' "$APP_MOCK"; then
  pass "Sourcery ran and generated the mock"
else
  fail "no mock was generated for App"
fi
# The compiler's own input list, written by this build, is what says the
# generated file reached the target — not a line in the log that could be the
# plugin naming its output directory.
APP_FILELIST="$(find "$DD/Build/Intermediates.noindex/XcodeFixture.build" \
  -path "*/App.build/*" -name App.SwiftFileList -type f 2>/dev/null | head -1)"
if [ -n "$APP_FILELIST" ] && grep -qF "$APP_MOCK" "$APP_FILELIST"; then
  pass "and Xcode compiled the generated file into the target"
else
  fail "the generated file is not in App's compile input list"
fi

# ── 2. Closure ────────────────────────────────────────────────────
# `${SOURCERY_SOURCES}` expands to the target's own input directories and nothing
# else. App depends on the `KitCore` product of a local package, and that
# dependency contributes nothing: `XcodeTarget.dependencies` is empty for a
# package product as well as for a sibling target (§1.3). Asserted, not assumed —
# an API that starts reporting dependency edges shows up here rather than
# silently changing what every consumer scans.
echo ""
echo "── closure ──"
APP_SOURCES="$(block_paths "$APP_CONFIG" sources)"
if [ "$APP_SOURCES" = "$FIXTURE_DIR/App" ]; then
  pass "one spliced directory: the target's own"
else
  fail "expected exactly '$FIXTURE_DIR/App', got: $(printf '%s\n' "$APP_SOURCES" | tr '\n' ' ')"
fi
if grep -q '${SOURCERY_PROJECT}/Libraries/Kit/Sources' "$APP_CONFIG"; then
  pass "the hand-listed entry beside the placeholder is carried through unexpanded"
else
  fail "the hand-listed source entry did not survive the splice"
fi

# ── 3. Hand-listed ────────────────────────────────────────────────
# The §2 rule, end to end: `cacheLimit` is declared one module away in `KitCore`
# and `report` two, in `KitLeaf`. Neither is reachable through the placeholder,
# both are reachable through the one line the author wrote, and a mock missing
# either does not compile against `acceptProfilePersisting`.
echo ""
echo "── hand-listed ──"
for requirement in "var profileID" "var cacheLimit" "func report"; do
  if grep -qF "$requirement" "$APP_MOCK" 2>/dev/null; then
    pass "the mock carries '$requirement'"
  else
    fail "the mock is missing '$requirement' — the hand-listed source directory was not scanned"
  fi
done

# ── 4. Passthrough ────────────────────────────────────────────────
echo ""
echo "── passthrough ──"
if check_passthrough "$FIXTURE_DIR/App/.Sourcery.Mocks.yml" "$APP_CONFIG" \
     '  - ${SOURCERY_SOURCES}'; then
  pass "every line but the placeholder is carried through verbatim"
else
  fail "the synthesized config does not carry the author's lines through"
fi

# ── 5. Defaults ───────────────────────────────────────────────────
# A config that says only what to generate is a complete config here too:
# `sources:` and `output:` are supplied, exactly as under SPM.
echo ""
echo "── defaults ──"
SOLO_LOG="$WORK_DIR/solo-build.log"
if ! xcbuild "$FIXTURE_DIR/XcodeFixture.xcodeproj" Solo "$DD" "$SOLO_LOG"; then
  grep -E 'error:' "$SOLO_LOG" | head -20
  fail "the Solo scheme did not build"
else
  SOLO_CONFIG="$(synthesized "$DD" Solo .Sourcery.Solo.yml)"
  SOLO_SOURCES="$(block_paths "$SOLO_CONFIG" sources)"
  if [ "$SOLO_SOURCES" = "$FIXTURE_DIR/Solo" ]; then
    pass "sources: appended, holding the target's own directory"
  else
    fail "sources: was not appended as expected (got '$SOLO_SOURCES')"
  fi
  SOLO_OUTPUT="$(grep '^output:' "$SOLO_CONFIG" | sed 's/^output: "//; s/"$//')"
  if [ -d "$SOLO_OUTPUT" ] && [ -f "$SOLO_OUTPUT/Mocks.generated.swift" ]; then
    pass "output: appended as an absolute path, and Sourcery generated into it"
  else
    fail "output: was not appended to an existing directory holding the generated file (got '$SOLO_OUTPUT')"
  fi
  if grep -q 'class GreetingMock' "$SOLO_OUTPUT/Mocks.generated.swift" 2>/dev/null; then
    pass "the zero-configuration target generated its mock"
  else
    fail "the zero-configuration target generated no mock"
  fi
fi

# ── 6. Determinism ────────────────────────────────────────────────
# The prebuild command re-runs on every build, so whatever the plugin writes at
# plan time has to be byte-identical between runs, or Sourcery's cache is
# invalidated every time.
echo ""
echo "── determinism ──"
SNAPSHOT="$WORK_DIR/configs-before"
rm -rf "$SNAPSHOT"; mkdir -p "$SNAPSHOT"
i=0
while IFS= read -r config; do
  i=$((i + 1))
  cp "$config" "$SNAPSHOT/$i-$(basename "$config")"
done < <(find "$DD/Build/Intermediates.noindex/BuildToolPluginIntermediates" -path "*/.sourceryConfigs/*" -type f | sort)

WARM_START=$SECONDS
xcbuild "$FIXTURE_DIR/XcodeFixture.xcodeproj" App "$DD" "$WORK_DIR/app-rebuild.log" || true
xcbuild "$FIXTURE_DIR/XcodeFixture.xcodeproj" Solo "$DD" "$WORK_DIR/solo-rebuild.log" || true
WARM_SECONDS=$((SECONDS - WARM_START))

DRIFT=0
i=0
while IFS= read -r config; do
  i=$((i + 1))
  if ! diff -q "$SNAPSHOT/$i-$(basename "$config")" "$config" > /dev/null; then
    diff -u "$SNAPSHOT/$i-$(basename "$config")" "$config" | head -10
    DRIFT=$((DRIFT + 1))
  fi
done < <(find "$DD/Build/Intermediates.noindex/BuildToolPluginIntermediates" -path "*/.sourceryConfigs/*" -type f | sort)
if [ "$DRIFT" = "0" ]; then
  pass "$i synthesized configs, all byte-identical on a second build (warm: ${WARM_SECONDS}s for both schemes)"
else
  fail "$DRIFT synthesized config(s) changed between two builds of the same project"
fi

# ── 7. Sibling target ─────────────────────────────────────────────
# `Dependent` depends on `Core`, a second framework target in the same project.
# The linked framework arrives in `Dependent`'s `inputFiles` as
# `<project>/build/Debug/Core.framework`, so the plugin derives `<project>/build`
# as a directory to look for configs in. That directory does not exist, and while
# the enumeration failure was reported as `Diagnostics.error`, every Xcode project
# with a dependency between two of its own targets failed at plan time. The second
# assertion is the other half: skipping the location that is missing must not lose
# the one that is there.
echo ""
echo "── sibling target ──"
DEP_LOG="$WORK_DIR/dependent-build.log"
if ! xcbuild "$FIXTURE_DIR/XcodeFixture.xcodeproj" Dependent "$DD" "$DEP_LOG"; then
  grep -E 'error:' "$DEP_LOG" | head -20
  fail "a target depending on a sibling target did not build"
else
  pass "a target depending on a sibling target builds"
  DEP_MOCK="$(generated "$DD" Dependent Sourcery.Dependent Mocks.generated.swift)"
  if [ -n "$DEP_MOCK" ] && grep -q 'class DispatchingMock' "$DEP_MOCK"; then
    pass "and its own config was still found and run"
  else
    fail "the Dependent target built, but its config was not found"
  fi
fi

# ── 8. Bare name ──────────────────────────────────────────────────
# The documented degradation, kept honest: an Xcode project has no package graph,
# so a bare template name cannot resolve to a shipped template. It must fail
# saying so, rather than generating nothing quietly.
echo ""
echo "── bare name ──"
BARE_LOG="$WORK_DIR/red-BareName.log"
if xcbuild "$RED_DIR/BareName/BareName.xcodeproj" BareName "$WORK_DIR/DD-BareName" "$BARE_LOG"; then
  fail "BareName built, and it must not: a bare template name has nothing to resolve against here"
elif grep -q "template 'Mocks' is neither a file beside the config nor a shipped template — no shipped templates are reachable from here" "$BARE_LOG"; then
  pass "a bare template name warns with the reason, and the build fails"
else
  tail -15 "$BARE_LOG"
  fail "BareName failed, but not with the expected diagnostic"
fi

# ── Result ────────────────────────────────────────────────────────
echo ""
if [ "$FAILURES" = "0" ]; then
  echo "ALL XCODE CHECKS PASSED  (cold ${COLD_SECONDS}s, warm ${WARM_SECONDS}s)"
else
  echo "$FAILURES CHECK(S) FAILED"
  exit 1
fi
